---
# yamllint disable rule:line-length
version: '3'

tasks:
  build:
    desc: Creates a cross platform binary
    cmds:
      - docker build . -t builder -f Dockerfile.pyinstaller --build-arg PYTHON_VERSION=$(cat .python-version)
      - >
        container=$(docker run --rm -d builder sleep 5) &&
        docker cp $container:/app/dist/borg-exporter ./dist/borg-exporter

  release:
    desc: Creates a Github release
    deps: [build]
    cmds:
      - git tag --delete latest
      - git tag -a latest -m 'Latest build'
      - >
        github-release delete
        --user danihodovic
        --repo borg-exporter
        --tag latest
      - >
        github-release release
        --user danihodovic
        --repo borg-exporter
        --tag latest
        --name borg-exporter
        --description "Borg exporter for Prometheus"
      - >
        github-release upload
        --user danihodovic
        --repo borg-exporter
        --tag latest
        --name borg-exporter
        --file ./dist/borg-exporter
